/*
  Warnings:

  - You are about to drop the `orders` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "orders";

-- CreateTable
CREATE TABLE "asks" (
    "id" BYTEA NOT NULL,
    "kind" TEXT,
    "side" TEXT,
    "status" TEXT,
    "token_set_Id" TEXT,
    "token_set_schema_hash" BYTEA,
    "contract" BYTEA,
    "maker" BYTEA,
    "taker" BYTEA,
    "price_currency_contract" BYTEA,
    "price_currency_name" TEXT,
    "price_currency_symbol" TEXT,
    "price_currency_decimals" INTEGER,
    "price_amount_raw" TEXT,
    "price_amount_decimal" DECIMAL,
    "price_amount_usd" DECIMAL,
    "price_amount_native" DECIMAL,
    "price_net_raw" TEXT,
    "price_net_decimal" DECIMAL,
    "price_net_usd" DECIMAL,
    "price_net_native" DECIMAL,
    "valid_from" INTEGER,
    "valid_until" INTEGER,
    "quantity_filled" INTEGER,
    "quantity_remaining" INTEGER,
    "dynamic_pricing" INTEGER,
    "criteria_kind" TEXT,
    "criteria_data_token_tokenId" TEXT,
    "criteria_data_token_name" TEXT,
    "criteria_data_token_image" TEXT,
    "criteria_data_collection_id" BYTEA,
    "criteria_data_collection_name" TEXT,
    "criteria_data_collection_image" TEXT,
    "source_id" BYTEA,
    "source_domain" TEXT,
    "source_name" TEXT,
    "source_icon" TEXT,
    "source_url" TEXT,
    "fee_bps" INTEGER,
    "fee_breakdown" JSON,
    "expiration" INTEGER,
    "is_reservoir" BOOLEAN,
    "is_dynamic" BOOLEAN,
    "updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3),

    CONSTRAINT "asks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bids" (
    "id" BYTEA NOT NULL,
    "kind" TEXT,
    "side" TEXT,
    "status" TEXT,
    "token_set_Id" TEXT,
    "token_set_schema_hash" BYTEA,
    "contract" BYTEA,
    "maker" BYTEA,
    "taker" BYTEA,
    "price_currency_contract" BYTEA,
    "price_currency_name" TEXT,
    "price_currency_symbol" TEXT,
    "price_currency_decimals" INTEGER,
    "price_amount_raw" TEXT,
    "price_amount_decimal" DECIMAL,
    "price_amount_usd" DECIMAL,
    "price_amount_native" DECIMAL,
    "price_net_raw" TEXT,
    "price_net_decimal" DECIMAL,
    "price_net_usd" DECIMAL,
    "price_net_native" DECIMAL,
    "valid_from" INTEGER,
    "valid_until" INTEGER,
    "quantity_filled" INTEGER,
    "quantity_remaining" INTEGER,
    "dynamic_pricing" INTEGER,
    "criteria_kind" TEXT,
    "criteria_data_token_tokenId" TEXT,
    "criteria_data_token_name" TEXT,
    "criteria_data_token_image" TEXT,
    "criteria_data_collection_id" BYTEA,
    "criteria_data_collection_name" TEXT,
    "criteria_data_collection_image" TEXT,
    "source_id" BYTEA,
    "source_domain" TEXT,
    "source_name" TEXT,
    "source_icon" TEXT,
    "source_url" TEXT,
    "fee_bps" INTEGER,
    "fee_breakdown" JSON,
    "expiration" INTEGER,
    "is_reservoir" BOOLEAN,
    "is_dynamic" BOOLEAN,
    "updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3),

    CONSTRAINT "bids_pkey" PRIMARY KEY ("id")
);
