-- AlterTable
ALTER TABLE "asks" ALTER COLUMN "quantity_filled" SET DATA TYPE BIGINT,
ALTER COLUMN "quantity_remaining" SET DATA TYPE BIGINT,
ALTER COLUMN "fee_bps" SET DATA TYPE BIGINT,
ALTER COLUMN "valid_from" SET DATA TYPE BIGINT,
ALTER COLUMN "valid_until" SET DATA TYPE BIGINT,
ALTER COLUMN "expiration" SET DATA TYPE BIGINT;
